# Generated by Django 6.0.1 on 2026-02-26 23:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0002_booking_restructure'),
        ('operations', '0006_remove_dailyport_sd_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Denormalized from BookingLine for easier querying', max_length=100, verbose_name='Contract Number'),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_records_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingline',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='agent',
            field=models.CharField(blank=True, max_length=200, verbose_name='Shipping Line / Agent'),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='vessel',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vessel Name'),
        ),
        # AlterModelTable removed - handled by migration 0008 idempotently
        # and model has db_table = 'ebooking_booking' set
        migrations.CreateModel(
            name='HistoricalBookingLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Contract Number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('booking_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ebooking.bookingrecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Booking Line',
                'verbose_name_plural': 'historical Booking Lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBookingRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sd_number', models.CharField(max_length=100, verbose_name='SD Number')),
                ('vessel', models.CharField(blank=True, max_length=200, verbose_name='Vessel Name')),
                ('agent', models.CharField(blank=True, max_length=200, verbose_name='Shipping Line / Agent')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sd_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.sdrecord')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Booking Record',
                'verbose_name_plural': 'historical Booking Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
