# Generated by Django 5.2.4 on 2026-02-27 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0005_bookingdetail_contract_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_text', models.TextField(help_text='Describe what needs to be corrected in the Bill of Lading', verbose_name='Correction Needed')),
                ('round_number', models.PositiveIntegerField(default=1, help_text='1st correction, 2nd correction, etc.', verbose_name='Correction Round')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='ebooking.bookingdetail', verbose_name='Booking Detail')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_corrections_created', to=settings.AUTH_USER_MODEL, verbose_name='Officer')),
            ],
            options={
                'verbose_name': 'Booking Correction',
                'verbose_name_plural': 'Booking Corrections',
                'ordering': ['booking_detail', 'round_number'],
            },
        ),
    ]
