# Generated by Django 5.2.4 on 2026-02-27 21:01

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0006_bookingcorrection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='booking_files/', validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='Document'),
        ),
    ]
