# Generated by Django 6.0.2 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0008_fix_table_rename_idempotent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcorrection',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='When the ebooking desk viewed this correction', null=True, verbose_name='Viewed At'),
        ),
    ]
