# Generated by Django 6.0.2 on 2026-03-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0009_bookingcorrection_viewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcorrection',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional: Attach scanned document or image showing the correction needed', null=True, upload_to='correction_attachments/', verbose_name='Attachment'),
        ),
    ]
