# Generated by Claude on 2026-03-16

from django.db import migrations


def backfill_booking_date(apps, schema_editor):
    """Backfill date field from created_at"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE ebooking_booking
            SET date = DATE(created_at)
            WHERE date IS NULL AND created_at IS NOT NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0011_correctionattachment'),
    ]

    operations = [
        # Use raw SQL to add column to correct table name (ebooking_booking, not ebooking_bookingrecord)
        migrations.RunSQL(
            sql='ALTER TABLE ebooking_booking ADD COLUMN date DATE NULL',
            reverse_sql='ALTER TABLE ebooking_booking DROP COLUMN date',
        ),
        migrations.RunPython(backfill_booking_date, reverse_code=migrations.RunPython.noop),
    ]
