# Generated by Claude on 2026-03-16

from django.db import migrations, connection


def add_date_column(apps, schema_editor):
    """Add date column to historical table (database-agnostic)."""
    # Check if column already exists
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name='ebooking_historicalbookingrecord'
                AND column_name='date'
            """)
            if not cursor.fetchone():
                cursor.execute('ALTER TABLE ebooking_historicalbookingrecord ADD COLUMN date DATE NULL')
        elif connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(ebooking_historicalbookingrecord)")
            columns = [row[1] for row in cursor.fetchall()]
            if 'date' not in columns:
                cursor.execute('ALTER TABLE ebooking_historicalbookingrecord ADD COLUMN date DATE NULL')


def remove_date_column(apps, schema_editor):
    """Remove date column from historical table (database-agnostic)."""
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute('ALTER TABLE ebooking_historicalbookingrecord DROP COLUMN IF EXISTS date')
        elif connection.vendor == 'sqlite':
            # SQLite doesn't support DROP COLUMN easily, so we skip reverse migration
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0012_bookingrecord_date'),
    ]

    operations = [
        migrations.RunPython(add_date_column, remove_date_column),
    ]
