# Generated by Django 6.0.1 on 2026-02-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_force_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
