# Generated by Django 6.0.1 on 2026-02-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_password_changed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_joined',
            new_name='first_login',
        ),
    ]
