# Generated by Django 6.0.1 on 2026-02-20 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_date_joined_account_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='first_login',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 20, 12, 22, 6, 5893, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
