# Generated by Django 6.0.1 on 2026-02-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='desk',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('OPERATIONS', 'Operations Desk'), ('EBOOKING', 'E-Booking Desk'), ('DECLARATION', 'Declaration Desk'), ('TERMINAL_SUPERVISOR', 'Terminal Supervisor'), ('EVACUATION', 'Evacuation Desk'), ('CLERK', 'Clerk / Other')], default='CLERK', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='is_contract_staff',
            field=models.BooleanField(default=False, help_text='Contract / temporary staff (uses placeholder staff number)'),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(choices=[('TEMA', 'Tema'), ('TAKORADI', 'Takoradi'), ('ACCRA', 'Accra'), ('KUMASI', 'Kumasi')], default='TEMA', max_length=30),
        ),
    ]
