# Generated by Django 6.0.1 on 2026-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_desk_account_is_contract_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_create_schedule',
            field=models.BooleanField(default=False, help_text='Allowed to create/edit loading schedules (e.g. deputy manager or acting manager)'),
        ),
    ]
