# Generated by Django 6.0.1 on 2026-02-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_can_create_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='desk',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('OPERATIONS', 'Operations Desk'), ('EBOOKING', 'E-Booking Desk'), ('DECLARATION', 'Declaration Desk'), ('TERMINAL_SUPERVISOR', 'Terminal Supervisor'), ('EVACUATION', 'Evacuation Desk'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
