# Generated by Django 5.2.4 on 2026-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract')], default='PERMANENT', max_length=20, verbose_name='Employment Type'),
        ),
    ]
