# Generated by Django 5.2.4 on 2026-02-27 21:01

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='can_create_schedule',
            field=models.BooleanField(default=False, help_text='Allowed to create/edit loading schedules (e.g. manager or deputy manager)'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='staffprofile', validators=[apps.core.validators.validate_image_file, apps.core.validators.validate_file_size_2mb]),
        ),
    ]
