# Generated by Django 6.0.1 on 2026-03-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_account_can_create_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='desks',
            field=models.JSONField(blank=True, default=list, help_text="List of desks this staff member is assigned to (e.g., ['OPERATIONS', 'EBOOKING'])"),
        ),
        migrations.AlterField(
            model_name='account',
            name='desk',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('OPERATIONS', 'Operations Desk'), ('EBOOKING', 'E-Booking Desk'), ('DECLARATION', 'Declaration Desk'), ('TERMINAL_SUPERVISOR', 'Terminal Supervisor'), ('EVACUATION', 'Evacuation Desk'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
