# Generated by Django 6.0.1 on 2026-03-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_migrate_desk_to_desks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='can_create_schedule',
        ),
    ]
