# Generated by Django 6.0.2 on 2026-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_can_create_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='date_employed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
