# Generated by Django 6.0.1 on 2026-02-22 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0003_containerlistupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Evacuation Date')),
                ('shift', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=10, verbose_name='Shift')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evacuation',
                'verbose_name_plural': 'Evacuations',
                'ordering': ['-date', 'shift'],
                'unique_together': {('date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='EvacuationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_number', models.CharField(max_length=100, verbose_name='SD Number')),
                ('allocation_label', models.CharField(blank=True, max_length=20, verbose_name='Allocation (A, B, C…)')),
                ('planned_count', models.PositiveIntegerField(default=0, verbose_name='Planned')),
                ('lifted_count', models.PositiveIntegerField(default=0, verbose_name='Lifted')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Failed')),
                ('notes', models.TextField(blank=True)),
                ('evacuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='evacuation.evacuation')),
                ('sd_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuation_lines', to='operations.sdrecord')),
            ],
            options={
                'verbose_name': 'Evacuation Line',
                'verbose_name_plural': 'Evacuation Lines',
                'ordering': ['sd_number', 'allocation_label'],
            },
        ),
    ]
