# Generated by Django 5.2.4 on 2026-02-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationline',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contract / MK Number'),
        ),
        migrations.CreateModel(
            name='EvacuationContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=100, verbose_name='Container Number')),
                ('status', models.CharField(choices=[('LIFTED', 'Lifted'), ('FAILED', 'Failed')], max_length=10, verbose_name='Status')),
                ('evacuation_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='evacuation.evacuationline')),
            ],
            options={
                'verbose_name': 'Evacuation Container',
                'verbose_name_plural': 'Evacuation Containers',
                'ordering': ['container_number'],
            },
        ),
    ]
