# Generated by Django 6.0.1 on 2026-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0002_revamp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationline',
            name='container_file',
            field=models.FileField(blank=True, null=True, upload_to='evacuation_files/', verbose_name='Container List File'),
        ),
    ]
