# Generated by Django 6.0.1 on 2026-02-27 00:07

from django.db import migrations, models


def add_shift_field_if_not_exists(apps, schema_editor):
    """
    Add shift field to evacuation table if it doesn't already exist.
    This is idempotent - safe to run multiple times.
    """
    with schema_editor.connection.cursor() as cursor:
        # Get database engine
        db_engine = schema_editor.connection.settings_dict['ENGINE']

        # Check if column exists
        if 'postgresql' in db_engine:
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name='evacuation_evacuation' AND column_name='shift'
            """)
        else:  # SQLite
            cursor.execute("PRAGMA table_info(evacuation_evacuation)")
            columns = [row[1] for row in cursor.fetchall()]
            cursor.execute("SELECT 1")  # Reset cursor

        result = cursor.fetchone()

        # Only add column if it doesn't exist
        if not result:
            cursor.execute("""
                ALTER TABLE evacuation_evacuation
                ADD COLUMN shift VARCHAR(10) DEFAULT 'DAY' NOT NULL
            """)


def reverse_add_shift_field(apps, schema_editor):
    """Remove shift field if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE evacuation_evacuation DROP COLUMN IF EXISTS shift")


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0005_add_vessel_field'),
    ]

    operations = [
        migrations.RunPython(add_shift_field_if_not_exists, reverse_add_shift_field),
    ]
