# Generated by Django 6.0.1 on 2026-02-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0006_add_shift_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evacuationline',
            options={'ordering': ['sd_number'], 'verbose_name': 'Evacuation Line', 'verbose_name_plural': 'Evacuation Lines'},
        ),
        migrations.RemoveField(
            model_name='evacuationline',
            name='allocation_label',
        ),
        migrations.RemoveField(
            model_name='evacuationline',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='evacuationline',
            name='failed_count',
        ),
        migrations.RemoveField(
            model_name='evacuationline',
            name='lifted_count',
        ),
        migrations.RemoveField(
            model_name='evacuationline',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='evacuationline',
            name='planned_count',
        ),
        migrations.AddField(
            model_name='evacuationline',
            name='agent',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agent'),
        ),
    ]
