# Generated by Django 5.2.4 on 2026-02-27 21:01

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0007_alter_evacuationline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evacuation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evacuationline',
            name='container_file',
            field=models.FileField(blank=True, null=True, upload_to='evacuation_files/', validators=[apps.core.validators.validate_excel_file, apps.core.validators.validate_file_size_25mb], verbose_name='Container List File'),
        ),
    ]
