# Generated by Django 6.0.1 on 2026-02-21 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_number', models.CharField(max_length=100, verbose_name='SD Number')),
                ('agent', models.CharField(max_length=200, verbose_name='Agent')),
                ('tonnage', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tonnage (MT)')),
                ('notes', models.TextField(blank=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='operations.schedule')),
            ],
            options={
                'ordering': ['sd_number'],
            },
        ),
        migrations.CreateModel(
            name='SDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_number', models.CharField(max_length=100, unique=True, verbose_name='SD Number')),
                ('si_ref', models.CharField(blank=True, max_length=100, verbose_name='SI Ref No.')),
                ('vessel_name', models.CharField(max_length=200, verbose_name='Vessel Name')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('tonnage', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Total Tonnage (MT)')),
                ('buyer', models.CharField(max_length=200, verbose_name='Buyer')),
                ('agent', models.CharField(max_length=200, verbose_name='Agent')),
                ('crop_year', models.CharField(blank=True, choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=20)),
                ('shipment_period', models.CharField(blank=True, max_length=100, verbose_name='Shipment Period')),
                ('port_of_loading', models.CharField(default='Takoradi', max_length=100)),
                ('port_of_discharge', models.CharField(blank=True, max_length=200)),
                ('container_size', models.CharField(default='40FT', max_length=50, verbose_name='Container Size')),
                ('bags_per_container', models.PositiveIntegerField(default=400)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Opening Balance (MT)')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Closing Balance (MT)')),
                ('stock_allocation_notes', models.TextField(blank=True, verbose_name='Additional Allocation Notes')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Fully Loaded / Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sd_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SD Record',
                'verbose_name_plural': 'SD Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SDClerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(blank=True, max_length=200, verbose_name='Clerk Name')),
                ('tally_reference', models.CharField(blank=True, max_length=100, verbose_name='Tally Reference')),
                ('date_worked', models.DateField(blank=True, null=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sd_clerk_entries', to=settings.AUTH_USER_MODEL)),
                ('sd_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerks', to='operations.sdrecord')),
            ],
            options={
                'ordering': ['date_worked', 'officer_name'],
            },
        ),
        migrations.CreateModel(
            name='SDAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_label', models.CharField(blank=True, max_length=10, verbose_name='Label (A, B, C…)')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Contract Number')),
                ('mk_number', models.CharField(max_length=100, verbose_name='MK No.')),
                ('allocated_tonnage', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Allocated Tonnage (MT)')),
                ('buyer', models.CharField(blank=True, max_length=200, verbose_name='Buyer')),
                ('agent', models.CharField(blank=True, max_length=200, verbose_name='Agent / Stock')),
                ('notes', models.TextField(blank=True)),
                ('sd_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='operations.sdrecord')),
            ],
            options={
                'ordering': ['allocation_label', 'contract_number'],
            },
        ),
        migrations.CreateModel(
            name='SDContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=100, verbose_name='Container No. (C/NO)')),
                ('seal_number', models.CharField(blank=True, max_length=100, verbose_name='Seal No.')),
                ('bag_count', models.PositiveIntegerField(default=400, verbose_name='No. of Bags')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Gross Weight (kg)')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Net Weight (kg)')),
                ('loading_date', models.DateField(blank=True, null=True, verbose_name='Date Loaded')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Balance After Loading (MT)')),
                ('tally_container_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Source TallyContainer ID')),
                ('from_tally', models.BooleanField(default=False, verbose_name='Auto-added from Tally')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='operations.sdallocation', verbose_name='Contract / Allocation')),
                ('sd_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='operations.sdrecord')),
            ],
            options={
                'ordering': ['loading_date', 'container_number'],
                'unique_together': {('sd_record', 'tally_container_id')},
            },
        ),
    ]
