# Generated by Django 6.0.1 on 2026-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdallocation',
            name='cocoa_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cocoa Type'),
        ),
        migrations.AddField(
            model_name='sdrecord',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Entry'),
        ),
        migrations.AddField(
            model_name='sdrecord',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('STRAIGHT', 'Straight'), ('BULK', 'Bulk')], max_length=20, verbose_name='Loading Type'),
        ),
        migrations.AddField(
            model_name='sdrecord',
            name='tonnage_loaded',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tonnage Loaded (MT)'),
        ),
        migrations.AlterField(
            model_name='sdrecord',
            name='port_of_loading',
            field=models.CharField(choices=[('TAKORADI', 'Takoradi'), ('TEMA', 'Tema'), ('KUMASI', 'Kumasi')], default='TAKORADI', max_length=100),
        ),
    ]
