# Generated by Django 6.0.1 on 2026-02-22 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_sdallocation_cocoa_type_sdrecord_date_of_entry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerListUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Contract Number')),
                ('tonnage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tonnage (MT)')),
                ('excel_file', models.FileField(upload_to='container_lists/', verbose_name='Container List (Excel)')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_list_uploads', to='operations.sdallocation', verbose_name='Contract / Allocation')),
                ('sd_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_list_uploads', to='operations.sdrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_lists_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Container List Upload',
                'verbose_name_plural': 'Container List Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
