# Generated by Django 5.2.4 on 2026-02-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_containerlistupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdrecord',
            name='sd_document',
            field=models.FileField(blank=True, null=True, upload_to='sd_documents/', verbose_name='SD Document'),
        ),
    ]
