# Generated by Django 6.0.1 on 2026-02-23 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_revamp_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sd_number', models.CharField(max_length=100, verbose_name='SD Number')),
                ('pdf_file', models.FileField(upload_to='daily_port/', verbose_name='PDF Document')),
                ('excel_file', models.FileField(upload_to='daily_port/', verbose_name='Excel File')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_ports_created', to=settings.AUTH_USER_MODEL)),
                ('sd_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_ports', to='operations.sdrecord', verbose_name='Linked SD Record')),
            ],
            options={
                'verbose_name': 'Daily Port',
                'verbose_name_plural': 'Daily Ports',
                'ordering': ['-date'],
            },
        ),
    ]
