# Generated by Django 6.0.1 on 2026-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_remove_dailyport_sd_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsdrecord',
            name='container_list',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Container List (Excel)'),
        ),
        migrations.AddField(
            model_name='sdrecord',
            name='container_list',
            field=models.FileField(blank=True, null=True, upload_to='container_lists/', verbose_name='Container List (Excel)'),
        ),
        migrations.AlterField(
            model_name='historicalsdrecord',
            name='sd_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='SD Document (PDF)'),
        ),
        migrations.AlterField(
            model_name='sdrecord',
            name='sd_document',
            field=models.FileField(blank=True, null=True, upload_to='sd_documents/', verbose_name='SD Document (PDF)'),
        ),
    ]
