# Generated by Django 6.0.1 on 2026-02-27 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_add_container_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsdrecord',
            name='officer_assigned',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Officer Assigned'),
        ),
        migrations.AddField(
            model_name='sdrecord',
            name='officer_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sd_records_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Officer Assigned'),
        ),
    ]
