# Generated by Django 5.2.4 on 2026-02-27 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_historicalsdrecord_officer_assigned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsdallocation',
            name='si_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='SI Ref'),
        ),
        migrations.AddField(
            model_name='sdallocation',
            name='si_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='SI Ref'),
        ),
    ]
