# Generated by Django 5.2.4 on 2026-02-27 21:01

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_historicalsdrecord_updated_by_sdrecord_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerlistupload',
            name='excel_file',
            field=models.FileField(upload_to='container_lists/', validators=[apps.core.validators.validate_excel_file, apps.core.validators.validate_file_size_25mb], verbose_name='Container List (Excel)'),
        ),
        migrations.AlterField(
            model_name='dailyport',
            name='excel_file',
            field=models.FileField(upload_to='daily_port/', validators=[apps.core.validators.validate_excel_file, apps.core.validators.validate_file_size_10mb], verbose_name='Excel File'),
        ),
        migrations.AlterField(
            model_name='dailyport',
            name='pdf_file',
            field=models.FileField(upload_to='daily_port/', validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='PDF Document'),
        ),
        migrations.AlterField(
            model_name='historicalcontainerlistupload',
            name='excel_file',
            field=models.TextField(max_length=100, validators=[apps.core.validators.validate_excel_file, apps.core.validators.validate_file_size_25mb], verbose_name='Container List (Excel)'),
        ),
        migrations.AlterField(
            model_name='historicaldailyport',
            name='excel_file',
            field=models.TextField(max_length=100, validators=[apps.core.validators.validate_excel_file, apps.core.validators.validate_file_size_10mb], verbose_name='Excel File'),
        ),
        migrations.AlterField(
            model_name='historicaldailyport',
            name='pdf_file',
            field=models.TextField(max_length=100, validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='PDF Document'),
        ),
        migrations.AlterField(
            model_name='historicalsdrecord',
            name='container_list',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[apps.core.validators.validate_excel_file, apps.core.validators.validate_file_size_25mb], verbose_name='Container List (Excel)'),
        ),
        migrations.AlterField(
            model_name='historicalsdrecord',
            name='sd_document',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='SD Document (PDF)'),
        ),
        migrations.AlterField(
            model_name='historicalworkprogram',
            name='pdf_file',
            field=models.TextField(help_text='Upload the work program document (PDF)', max_length=100, validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='Work Program PDF'),
        ),
        migrations.AlterField(
            model_name='sdrecord',
            name='container_list',
            field=models.FileField(blank=True, null=True, upload_to='container_lists/', validators=[apps.core.validators.validate_excel_file, apps.core.validators.validate_file_size_25mb], verbose_name='Container List (Excel)'),
        ),
        migrations.AlterField(
            model_name='sdrecord',
            name='sd_document',
            field=models.FileField(blank=True, null=True, upload_to='sd_documents/', validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='SD Document (PDF)'),
        ),
        migrations.AlterField(
            model_name='workprogram',
            name='pdf_file',
            field=models.FileField(help_text='Upload the work program document (PDF)', upload_to='work_programs/', validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='Work Program PDF'),
        ),
    ]
