# Generated by Django 6.0.2 on 2026-03-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_containerlistupload_excel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsdallocation',
            name='tonnage_loaded',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Tonnage Loaded (MT)'),
        ),
        migrations.AddField(
            model_name='sdallocation',
            name='tonnage_loaded',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Tonnage Loaded (MT)'),
        ),
    ]
