# Generated by Django 6.0.1 on 2026-01-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_number', models.PositiveBigIntegerField(unique=True)),
                ('tally_type', models.CharField(choices=[('BULK', 'BULK_LOADING'), ('STRAIGHT_20FT', 'STRAIGHT_20FT'), ('STRAIGHT_40FT', 'STRAIGHT_40FT'), ('JAPAN_STRAIGHT_40FT', 'JAPAN_STRAIGHT_40FT')], max_length=30)),
                ('produce', models.CharField(default='RAW COCOA BEANS', max_length=100)),
                ('crop_year', models.CharField(max_length=30)),
                ('sd_number', models.CharField(max_length=20)),
                ('mk_number', models.CharField(max_length=20)),
                ('vessel', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=50)),
                ('loading_date', models.DateField()),
                ('marks_and_numbers', models.CharField(max_length=100)),
                ('superintendent_type', models.CharField(choices=[('NONE', 'NONE'), ('JLB', 'JLB'), ('CWT', 'CWT'), ('CWT + JLB', 'CWT + JLB')], default='NONE', max_length=20)),
                ('superintendent_name', models.JSONField(blank=True, default=list)),
                ('clerk_name', models.JSONField(default=list)),
                ('dry_bags', models.PositiveIntegerField(blank=True, null=True)),
                ('total_bags', models.PositiveIntegerField(default=0)),
                ('total_tonnage', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('expected_bags', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_bags', models.PositiveIntegerField(blank=True, null=True)),
                ('bags_saved', models.IntegerField(default=0)),
                ('seller_codes', models.JSONField(blank=True, default=list)),
                ('color_tag_entries', models.JSONField(blank=True, default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TallyContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=30)),
                ('seal_number', models.CharField(max_length=30)),
                ('tonnage', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bags_cut', models.PositiveIntegerField(blank=True, null=True)),
                ('bags', models.PositiveIntegerField(blank=True, null=True)),
                ('container_photo', models.ImageField(upload_to='pics/containers/')),
                ('seal_photo', models.ImageField(upload_to='pics/seals/')),
                ('tally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='tally.tallyinfo')),
            ],
        ),
    ]
