# Generated by Django 6.0.1 on 2026-01-26 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallycontainer',
            name='tally',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='tally.tallyinfo'),
        ),
    ]
