# Generated by Django 6.0.1 on 2026-01-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0002_alter_tallycontainer_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyinfo',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('STRAIGHT', 'STRAIGHT'), ('BULK', 'BULK')], null=True),
        ),
        migrations.AddField(
            model_name='tallyinfo',
            name='straight_type',
            field=models.CharField(blank=True, choices=[('BULK', 'BULK'), ('STRAIGHT_20FT', 'STRAIGHT_20FT'), ('STRAIGHT_40FT', 'STRAIGHT_40FT'), ('JAPAN_STRAIGHT_40FT', 'JAPAN_STRAIGHT_40FT')], null=True),
        ),
        migrations.AlterField(
            model_name='tallycontainer',
            name='tally',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='tally.tallyinfo'),
        ),
    ]
