# Generated by Django 6.0.1 on 2026-01-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0003_tallyinfo_loading_type_tallyinfo_straight_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tallycontainer',
            options={'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='tallyinfo',
            options={'verbose_name': 'Tally', 'verbose_name_plural': 'TALLIES'},
        ),
        migrations.AlterField(
            model_name='tallyinfo',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('STRAIGHT', 'STRAIGHT'), ('BULK', 'BULK')], max_length=20, null=True),
        ),
    ]
