# Generated by Django 6.0.1 on 2026-01-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0004_alter_tallycontainer_options_alter_tallyinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyinfo',
            name='dry_bags',
            field=models.CharField(blank=True, null=True),
        ),
    ]
