# Generated by Django 6.0.1 on 2026-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0006_tallyinfo_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallyinfo',
            name='created_by',
        ),
        migrations.AddField(
            model_name='tallyinfo',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
