# Generated by Django 6.0.1 on 2026-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0007_remove_tallyinfo_created_by_tallyinfo_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyinfo',
            name='cocoa_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
