# Generated by Django 5.2.4 on 2026-02-23 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0009_tallyinfo_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyinfo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tallyinfo',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tallies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tallyinfo',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tallyinfo',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='tallyinfo',
            name='terminal_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(choices=[('TEMA', 'Tema'), ('TAKORADI', 'Takoradi'), ('ACCRA', 'Accra'), ('KUMASI', 'Kumasi')], default='TEMA', max_length=30)),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervised_terminals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
            },
        ),
        migrations.AlterField(
            model_name='tallyinfo',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tallies', to='tally.terminal'),
        ),
    ]
