# Generated by Django 5.2.4 on 2026-02-27 21:01

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0010_revamp_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallycontainer',
            name='container_photo',
            field=models.ImageField(upload_to='pics/containers/', validators=[apps.core.validators.validate_image_file, apps.core.validators.validate_file_size_5mb]),
        ),
        migrations.AlterField(
            model_name='tallycontainer',
            name='seal_photo',
            field=models.ImageField(upload_to='pics/seals/', validators=[apps.core.validators.validate_image_file, apps.core.validators.validate_file_size_5mb]),
        ),
    ]
