# Generated by Django 6.0.1 on 2026-03-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0011_alter_tallycontainer_container_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallycontainer',
            name='container_photo',
        ),
        migrations.RemoveField(
            model_name='tallycontainer',
            name='seal_photo',
        ),
    ]
