# Generated by Django 6.0.1 on 2026-03-02 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_containerlistupload_excel_file_and_more'),
        ('tally', '0012_remove_photo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyinfo',
            name='sd_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tallies', to='operations.sdrecord', verbose_name='Linked SD Record'),
        ),
    ]
