# Generated by Django 6.0.1 on 2026-03-03 08:32

from django.db import migrations, connection


def add_sd_record_column(apps, schema_editor):
    """
    Add sd_record_id column if it doesn't exist.
    This fixes the issue where migration 0013 was marked as applied
    but the column was never created in the production database.
    """
    with connection.cursor() as cursor:
        db_vendor = connection.vendor

        # Check if column exists
        try:
            cursor.execute("SELECT * FROM tally_tallyinfo LIMIT 0")
            columns = [col[0] for col in cursor.description]

            if 'sd_record_id' in columns:
                print('Column sd_record_id already exists')
                return
        except Exception as e:
            print(f'Error checking columns: {e}')
            # Continue anyway - try to add the column

        print('Adding sd_record_id column...')

        if db_vendor == 'postgresql':
            # PostgreSQL: Drop constraint if exists, then add column and constraint
            try:
                cursor.execute("""
                    ALTER TABLE tally_tallyinfo
                    DROP CONSTRAINT IF EXISTS tally_tallyinfo_sd_record_id_fkey
                """)
            except Exception as e:
                print(f'Note: Could not drop constraint (may not exist): {e}')

            try:
                cursor.execute("""
                    ALTER TABLE tally_tallyinfo
                    ADD COLUMN IF NOT EXISTS sd_record_id INTEGER NULL
                """)
                print('Column added')
            except Exception as e:
                print(f'Error adding column: {e}')
                raise

            try:
                cursor.execute("""
                    ALTER TABLE tally_tallyinfo
                    ADD CONSTRAINT tally_tallyinfo_sd_record_id_fkey
                    FOREIGN KEY (sd_record_id)
                    REFERENCES operations_sdrecord(id)
                    ON DELETE SET NULL
                """)
                print('Foreign key constraint added')
            except Exception as e:
                print(f'Warning: Could not add foreign key constraint: {e}')
                # Don't raise - column is more important than constraint

        elif db_vendor == 'sqlite':
            # SQLite syntax
            try:
                cursor.execute("""
                    ALTER TABLE tally_tallyinfo
                    ADD COLUMN sd_record_id INTEGER NULL
                """)
                print('Column added')
            except Exception as e:
                print(f'Error adding column: {e}')
                raise

        print('Migration completed successfully')


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0013_tallyinfo_sd_record'),
    ]

    operations = [
        migrations.RunPython(add_sd_record_column, migrations.RunPython.noop),
    ]
