# Generated by Django 6.0.1 on 2026-03-03 08:39

from django.db import migrations, connection


def add_sd_record_column_robust(apps, schema_editor):
    """
    Robustly add sd_record_id column with better error handling.
    Uses PostgreSQL IF NOT EXISTS syntax.
    """
    import sys
    from django.conf import settings

    # DEBUG: Print database configuration during migration
    sys.stdout.write("\n" + "=" * 80 + "\n")
    sys.stdout.write("[MIGRATION 0015] Starting migration...\n")
    sys.stdout.write(f"[MIGRATION 0015] connection.vendor = {connection.vendor}\n")
    sys.stdout.write(f"[MIGRATION 0015] DATABASES config = {settings.DATABASES['default']['ENGINE']}\n")
    sys.stdout.write(f"[MIGRATION 0015] Database HOST = {settings.DATABASES['default'].get('HOST', 'N/A')}\n")
    sys.stdout.write(f"[MIGRATION 0015] Database NAME = {settings.DATABASES['default'].get('NAME', 'N/A')}\n")
    sys.stdout.write("=" * 80 + "\n")
    sys.stdout.flush()

    with connection.cursor() as cursor:
        db_vendor = connection.vendor

        if db_vendor == 'postgresql':
            print('PostgreSQL detected - adding column with IF NOT EXISTS')

            # Add column if not exists (PostgreSQL 9.6+)
            try:
                cursor.execute("""
                    ALTER TABLE tally_tallyinfo
                    ADD COLUMN IF NOT EXISTS sd_record_id INTEGER NULL
                """)
                print('Column sd_record_id added or already exists')
            except Exception as e:
                print(f'Error adding column: {e}')
                raise

            # Add foreign key constraint if not exists
            try:
                # Check if constraint exists
                cursor.execute("""
                    SELECT constraint_name
                    FROM information_schema.table_constraints
                    WHERE table_name = 'tally_tallyinfo'
                    AND constraint_name = 'tally_tallyinfo_sd_record_id_fkey'
                """)

                if cursor.fetchone() is None:
                    cursor.execute("""
                        ALTER TABLE tally_tallyinfo
                        ADD CONSTRAINT tally_tallyinfo_sd_record_id_fkey
                        FOREIGN KEY (sd_record_id)
                        REFERENCES operations_sdrecord(id)
                        ON DELETE SET NULL
                    """)
                    print('Foreign key constraint added')
                else:
                    print('Foreign key constraint already exists')
            except Exception as e:
                print(f'Warning: Could not add foreign key constraint: {e}')
                # Don't raise - column is more important

        elif db_vendor == 'sqlite':
            print('SQLite detected - checking if column exists')

            # Check if column exists
            cursor.execute("SELECT * FROM tally_tallyinfo LIMIT 0")
            columns = [col[0] for col in cursor.description]

            if 'sd_record_id' not in columns:
                cursor.execute("""
                    ALTER TABLE tally_tallyinfo
                    ADD COLUMN sd_record_id INTEGER NULL
                """)
                print('Column sd_record_id added')
            else:
                print('Column sd_record_id already exists')

        print('Migration 0015 completed successfully')


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0014_fix_missing_sd_record_column'),
    ]

    operations = [
        migrations.RunPython(add_sd_record_column_robust, migrations.RunPython.noop),
    ]
