# Generated by Django 6.0.1 on 2026-03-03 08:54

from django.db import migrations, connection


def add_column_if_missing(apps, schema_editor):
    """
    Add sd_record_id column using raw SQL.
    Works with both SQLite and PostgreSQL.
    """
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("SELECT * FROM tally_tallyinfo LIMIT 0")
        columns = [col[0] for col in cursor.description]

        if 'sd_record_id' in columns:
            print('Column sd_record_id already exists - skipping')
            return

        print('Adding sd_record_id column...')

        db_vendor = connection.vendor

        if db_vendor == 'postgresql':
            # PostgreSQL
            cursor.execute("""
                ALTER TABLE tally_tallyinfo
                ADD COLUMN sd_record_id INTEGER NULL
            """)

            # Add foreign key constraint
            cursor.execute("""
                ALTER TABLE tally_tallyinfo
                ADD CONSTRAINT tally_tallyinfo_sd_record_id_fkey
                FOREIGN KEY (sd_record_id)
                REFERENCES operations_sdrecord(id)
                ON DELETE SET NULL
            """)
            print('Column and constraint added successfully')

        elif db_vendor == 'sqlite':
            # SQLite
            cursor.execute("""
                ALTER TABLE tally_tallyinfo
                ADD COLUMN sd_record_id INTEGER NULL
            """)
            print('Column added successfully')


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_add_sd_record_column_robust'),
    ]

    operations = [
        migrations.RunPython(add_column_if_missing, migrations.RunPython.noop),
    ]
