# Generated by Django 6.0.2 on 2026-03-08 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0017_tallyinfo_updated_at_tallyinfo_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting recall')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Operations Approval'), ('APPROVED', 'Approved - Tally Recalled'), ('REJECTED', 'Rejected by Operations')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('operations_notes', models.TextField(blank=True, help_text='Notes from operations desk when processing request')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Operations staff who approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Supervisor who requested the recall', on_delete=django.db.models.deletion.PROTECT, related_name='recall_requests_made', to=settings.AUTH_USER_MODEL)),
                ('tally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_requests', to='tally.tallyinfo')),
            ],
            options={
                'verbose_name': 'Recall Request',
                'verbose_name_plural': 'Recall Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
