# Generated by Django 6.0.1 on 2026-02-22 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0003_containerlistupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_number', models.CharField(max_length=100, verbose_name='SD Number')),
                ('agent', models.CharField(blank=True, max_length=200, verbose_name='Agent')),
                ('vessel', models.CharField(blank=True, max_length=200, verbose_name='Vessel')),
                ('declaration_number', models.CharField(max_length=100, verbose_name='Declaration Number')),
                ('tonnage', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tonnage Declared (MT)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_created', to=settings.AUTH_USER_MODEL)),
                ('sd_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='operations.sdrecord')),
            ],
            options={
                'verbose_name': 'Declaration',
                'verbose_name_plural': 'Declarations',
                'ordering': ['-created_at'],
            },
        ),
    ]
