# Generated by Django 5.2.4 on 2026-02-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contract Number'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='declaration_pdf',
            field=models.FileField(blank=True, null=True, upload_to='declaration_docs/', verbose_name='Declaration Document'),
        ),
    ]
