# Generated by Django 6.0.1 on 2026-02-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0002_revamp_models'),
        ('operations', '0005_dailyport'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='operations.sdallocation', verbose_name='Contract / Allocation'),
        ),
    ]
