# Generated by Django 5.2.4 on 2026-02-27 21:01

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0003_declaration_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_pdf',
            field=models.FileField(blank=True, null=True, upload_to='declaration_docs/', validators=[apps.core.validators.validate_pdf_file, apps.core.validators.validate_file_size_10mb], verbose_name='Declaration Document'),
        ),
    ]
