# Generated by Claude on 2026-03-15

import django.utils.timezone
from django.db import migrations, models


def backfill_declaration_date(apps, schema_editor):
    Declaration = apps.get_model('declaration', 'Declaration')
    for d in Declaration.objects.all().only('id', 'created_at', 'date'):
        if d.date is None and d.created_at is not None:
            d.date = d.created_at.date()
            d.save(update_fields=['date'])


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0005_declaration_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_declaration_date, reverse_code=migrations.RunPython.noop),
    ]
